+CSCI_GrpDesktop = True
executable=/research/hutchinson/workspace/fettigj/ml_climate_gcam22/run.sh
batch_name=active
request_cpus=8
request_gpus=1
request_memory=8GB
output=/research/hutchinson/workspace/fettigj/transformers2_electric_boogaloo/logs/condor_logs/out.$(clusterid).$(procid).txt
error =/research/hutchinson/workspace/fettigj/transformers2_electric_boogaloo/logs/condor_logs/err.$(clusterid).$(procid).txt
log=logs/condor.log
max_idle=20


# queue arguments from [:] /research/hutchinson/workspace/fettigj/ml_climate_gcam22/active_args.txt
# output=logs/condor_logs/out.$(clusterid).$(procid).txt
# error =logs/condor_logs/err.$(clusterid).$(procid).txt
