+CSCI_GrpDesktop = True
executable=/research/hutchinson/workspace/fettigj/transformers2_electric_boogaloo/jobs/run.sh

request_cpus=8
request_gpus=1
request_memory=8GB
gpus_minimum_memory=10G

output=/research/hutchinson/workspace/fettigj/transformers2_electric_boogaloo/logs/condor_logs/out.$(args).$(procid).txt
error =/research/hutchinson/workspace/fettigj/transformers2_electric_boogaloo/logs/condor_logs/err.$(args).$(procid).txt
log   =/research/hutchinson/workspace/fettigj/transformers2_electric_boogaloo/logs/condor_logs/condor.log

max_idle=20
queue 20
